### 10 Глава. Обработка исключений.
  
Операторы try/catсh - перехыватывают исключения во время исполнения кода.
Исключение в Java представляет собой объект, описывающий исключительную (т.е. ошибочную) ситуацию, возникающую в определенной части программного кода.
Если исключение возникает в блоке try, оно генерирует объект Exception. Прикладной код может перехватить исключение, используя блок catch, а затем обработать его некоторым рациональным способом. 
Системные исключения ***автоматически*** генерируются
исполняющей системой Java. 
Для генерирования исключения вручную
служит ключевое слово throw.

Любое исключение, генерируемое в теле метода, должно быть обозначено в его объявлении ключевым словом throws.

А любой код, который должен быть непременно выполнен по завершении блока try , размещается в блоке finally. Ниже приведена общая форма блока обработки исклю­чений.

### Типы исключений

Все типы исключений являются подклассами, производными от встроенного класса Throwable, его подклассами являются Error и Exception.

Exception - класс для исключительных условия, которые должна перехватывать программа, именно от него мы и наследуем свои подклассы при создании собственных типов исключений. 
Он имеет вложенй подкласс RuntimeException - исключения этого типа определяются как создваваемые Програмистом( деление на ноль, ошибка индексации массивов).

Error же определяет тот тип исключений, появление который не предпологается при нормальной работе программы. 
`Error` используется в испольняющей системе Java для обозначения ошибок, происходящий в самой испольняющей среде, например, переполнение стека. Erorr как правило возникают в связи с аварийными сбоями, которые не могут быть обработаны в прикладной программе.

### Необрабатываемые исключения

Когда исполняющая система Jаvа обнаруживает попытку деления на нуль, она создает новый объект исключения, а затем геиерирует исключение. Это прерывает выполнение класса, ведь как только исключение сгенерировано, оно должно быть перехвачено обработчиком исключений и немедленно обработано. 

Если обработчик исключений отсутствует в прикладной программе, значит исключение будет перехвачено стандартным обработчиком исключений Java. Он выводит символьную строку в консоль, содержающую имя класса, метода и строку. Трассировка стека позволяет отследить возинкающую ошибку с учетом последовательности вызова в стеке.

### Ипользование try and catch

Идут в связке как единое целое. 

try можно использовать без catch, но не имеет смысла.

только если лень закрывать ресурсы.

Использование блоков позволяет обработать исключение и исправить ошибку и не прерывать программу. 

Как только возникает исключение в блоке try управление передается сразу блоку catch. После работы catch управление передается блоку после него.

Оператор catch перехваьтывает только то исключение которое возникает в вышестоящем блоке try

Целью большинства правильно построенных операторов catch является разрешение исключительных ситуаций и продолжение нормальной работы программы, как если бы ошибки вообще не было.

### Несколько операторов catch

Когда генерируется исключение в блоке try, каждый оператор catch проверяется по порядку и выполняется тот из них ,который совпадает по типу, по завешению блока catch, остальные пропускаются и работа программы продолжается с оператора следующиего после блока try

Применяя несколько операторов catch, важно помнить, что перехват исклю­чений из подклассов должен следовать до перехвата исключений из суперклассов. **СОБЛЮДЕНИЕ ИЕРАРХИИ КЛАССОВ ИСКЛЮЧЕНИЙ.** 
Дело в том, что оператор catch будет перехватывать все искелючения суперкласса и его подклассов. А это означает, что исключения подклассав, вообще не будут обработаны. **Это приводит к недостижимому коду.**

### Вложенные операторы try

Это означает, что один оператор try может находится в блоке другого оператора try. 

Если во вложенном блоке try исключение не обрабатывается, то исключение передается во внешний блок catch и так до тех пор пока не найдется соответствующий обработчик ошибки.  

### Оператор throw

Генерирует исключение в приккладонй программе. Экземлпяр должен быть объектом класса ThrowaЫe. Получить объект Throwable можно двумя способами, в блоке catch или c  при помощи оператора new.

 Поток испольнения останавливается сразуже после блока throw. Ближайший оъемлющий блок сразу же проверяется на поиск оператора catch. Если его найти не удается, ошибку перехватывает стандартный обработчик выводя прерывая выполнения программы и выводит результат с трассировкой стека.

### Оператор throws

Если метод способен вызвать исключение, которое он сам не обрабатывает,
то он должен задать свое поведение таким образом, чтобы вызывающий его код
мог обезопасить себя от такого исключения. То есть указывает, какое исключение он может вызывать. А привызове метода, его вызывают в блоке try, который и обработает это исключение.

С этой целью в объявление метода
вводится оператор throws, где перечисляются типы исключений, которые ме­
тод может генерировать. В объявлении метода, их можно писать через запятую.

### Оператор finally

Когда генерируется исклчюение, испсолнение метода идет по неленейному пути, резко меняющему последовательность выполнения операторов в теле метода.

Выполняется по завершению блока try/cathс.

Выполняется независимо от того сгенерировано ли исключение или нет. И даже до оператора return.

Каждому оператору try требуется  1оператор catch/finally.

### Встроенные в Java исключения

### Создание собственных подклассов исключений

Создается класс, наследуется от Exeption. Не обязательно реализовывать, что -нибудь, Достаточно их наличия в системе, чтобы ими уже пользоваться.

Существуеут 2 конструктора исключений, без конструктора и с сообщением в виде аргумента конструктора. Указывать описание исключение при его создании иногда очень удобно, но иногда лучше переопределит ьметод toString

### Цепочки исключений

C jdk 1.4 было внедрено средство, называемое цепочками исключений, которое позволяет связывать одно исключение с другим, чтобы описывать в последнем причину первого. 

Чтобы разрешить цепочки исключений, в класс ThrowaЫe были введены два
конструктора и два метода. Ниже приведены общие формы конструкторов.
ТhrovaЫe (ТhrovaЫe пр11чяна ясхлJОЧения)
ТhrovaЫe (Strinq сообщение,-ТhrоvаЫе пр•чяна_11сЖЛJОЧения)

Метод getCause ( ) возвращает исключение, вызывающее текущее исключе­
ние. Если же такое исключение отсутствует, то возвращается пустое значение
null. 

Метод initCause ( ) связывает причину_ исключения с вызывающим ис­
ключением и возвращает ссылку на исключение.

<aside>
💡 Причина исключения может быть ыустановлена только один раз.

</aside>

Вообще метод ini tCause ( ) служит для уста­новки причины исключений из устаревших классов, где оба упомянутых выше до­полнительных конструктора не поддерживаются.

Вызывая у исключение метод initCause, в нем мы можем создать причину исклчюения и добавить туда исклчюение другое.

Это означает, что причина исключения может не иметь собственную причину.

### Недавно внедренные средства для обработки исключений

- tra with resources
- Многократный перехват - позволяет перехватыывать несколько исключений в одном блоке try
- Окончательное повторное генерирование исключения - ограничива­ет их тип только теми проверяемыми исключениями, которые связаны с блоком оператора try, где они генерируются, но не обрабатываются предыдущим опера­ тором catch и являются подтипом или супертипом его параметра.
